export const ProductsData = [
  {
    id: "1",
    gender: "man",
    name: "Check Lightweight",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "74.95",
    category: "shirt",
    imageUrl: "shirt-man",
    imageFormat: ".webp",
    url: require("../assets/images/shirt-man/Check Lightweight.webp"),
  },
  {
    id: "2",
    gender: "man",
    name: "Shirt with",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "84.95",
    category: "shirt",
    imageUrl: "shirt-man",
    imageFormat: ".webp",
    url: require("../assets/images/shirt-man/Shirt with.webp"),
  },
  {
    id: "3",
    gender: "man",
    name: "Solid Oxfordwevp",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "74.95",
    category: "shirt",
    imageUrl: "shirt-man",
    imageFormat: ".webp",
    url: require("../assets/images/shirt-man/Solid Oxfordwevp.webp"),
  },
  {
    id: "4",
    gender: "man",
    name: "Stripe Lightweight",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "106",
    category: "shirt",
    imageUrl: "shirt-man",
    imageFormat: ".webp",
    url: require("../assets/images/shirt-man/Stripe Lightweight.webp"),
  },
  {
    id: "5",
    gender: "man",
    name: "eComfort",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "84",
    category: "shoes",
    imageUrl: "shoes-man",
    imageFormat: ".webp",
    url: require("../assets/images/shoes-man/eComfort.webp"),
  },
  {
    id: "6",
    gender: "man",
    name: "Golf Sandals",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "129",
    category: "shoes",
    imageUrl: "shoes-man",
    imageFormat: ".webp",
    url: require("../assets/images/shoes-man/Golf Sandals.webp"),
  },
  {
    id: "7",
    gender: "man",
    name: "Premiere Series",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "199",
    category: "shoes",
    imageUrl: "shoes-man",
    imageFormat: ".webp",
    url: require("../assets/images/shoes-man/Premiere Series.webp"),
  },
  {
    id: "8",
    gender: "man",
    name: "Winter Golf Boots",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "129.99",
    category: "shoes",
    imageUrl: "shoes-man",
    imageFormat: ".webp",
    url: require("../assets/images/shoes-man/Winter Golf Boots.webp"),
  },
  {
    id: "9",
    gender: "man",
    name: "black watch",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "500",
    category: "watch",
    imageUrl: "watch",
    imageFormat: ".webp",
    url: require("../assets/images/watch/black watch.webp"),
  },
  {
    id: "10",
    gender: "man",
    name: "classice watch",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "800",
    category: "watch",
    imageUrl: "watch",
    imageFormat: ".webp",
    url: require("../assets/images/watch/classice watch.webp"),
  },
  {
    id: "11",
    gender: "man",
    name: "green watch",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "680",
    category: "watch",
    imageUrl: "watch",
    imageFormat: ".webp",
    url: require("../assets/images/watch/green watch.webp"),
  },
  {
    id: "12",
    gender: "man",
    name: "ts watch",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "680",
    category: "watch",
    imageUrl: "watch",
    imageFormat: ".webp",
    url: require("../assets/images/watch/ts watch.webp"),
  },

  {
    id: "13",
    gender: "woman",
    name: "Long Sleeve Sun",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "88",
    category: "shirt",
    imageUrl: "shirt-woman",
    imageFormat: ".webp",
    url: require("../assets/images/shirt-woman/Long Sleeve Sun.webp"),
  },
  {
    id: "14",
    gender: "woman",
    name: "Sleeve Sun shirt",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "68",
    category: "shirt",
    imageUrl: "shirt-woman",
    imageFormat: ".webp",
    url: require("../assets/images/shirt-woman/Sleeve Sun shirt.webp"),
  },
  {
    id: "15",
    gender: "woman",
    name: "Solid Lisle Self",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "95",
    category: "shirt",
    imageUrl: "shirt-woman",
    imageFormat: ".webp",
    url: require("../assets/images/shirt-woman/Solid Lisle Self.webp"),
  },
  {
    id: "16",
    gender: "woman",
    name: "Solid Lisle Sleeveless",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "80",
    category: "shirt",
    imageUrl: "shirt-woman",
    imageFormat: ".webp",
    url: require("../assets/images/shirt-woman/Solid Lisle Sleeveless.webp"),
  },
  {
    id: "17",
    gender: "woman",
    name: "Bayswater Tote",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "82",
    category: "bag",
    imageUrl: "bag-woman",
    imageFormat: ".jpg",
    url: require("../assets/images/bag-woman/Bayswater Tote.jpg"),
  },
  {
    id: "18",
    gender: "woman",
    name: "Chalk Heavy",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "122",
    category: "bag",
    imageUrl: "bag-woman",
    imageFormat: ".jpg",
    url: require("../assets/images/bag-woman/Chalk Heavy.jpg"),
  },
  {
    id: "19",
    gender: "woman",
    name: "Oak Natural",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "117",
    category: "bag",
    imageUrl: "bag-woman",
    imageFormat: ".jpg",
    url: require("../assets/images/bag-woman/Oak Natural.jpg"),
  },
  {
    id: "20",
    gender: "woman",
    name: "Small Pink",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "135",
    category: "bag",
    imageUrl: "bag-woman",
    imageFormat: ".jpg",
    url: require("../assets/images/bag-woman/Small Pink.jpg"),
  },
  {
    id: "21",
    gender: "woman",
    name: "Flex Coastal Women",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "109",
    category: "shoes",
    imageUrl: "shoes-woman",
    imageFormat: ".webp",
    url: require("../assets/images/shoes-woman/Flex Coastal Women.webp"),
  },
  {
    id: "22",
    gender: "woman",
    name: "Flex XP Women",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "99",
    category: "shoes",
    imageUrl: "shoes-woman",
    imageFormat: ".webp",
    url: require("../assets/images/shoes-woman/Flex XP Women.webp"),
  },
  {
    id: "23",
    gender: "woman",
    name: "Leisure Women",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "120",
    category: "shoes",
    imageUrl: "shoes-woman",
    imageFormat: ".webp",
    url: require("../assets/images/shoes-woman/Leisure Women.webp"),
  },
  {
    id: "24",
    gender: "woman",
    name: "Stratos Women",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure quisquam eos quis consequuntur nesciunt quasi odio saepe et, sapiente aperiam cumque velit optio reiciendis corrupti vero, neque, nam officiis nihil.",
    price: "199",
    category: "shoes",
    imageUrl: "shoes-woman",
    imageFormat: ".webp",
    url: require("../assets/images/shoes-woman/Stratos Women.webp"),
  },
];
